version: '2'

services:
  client:
    build: angular-client
    ports:
      - "4200:4200"
    volumes:
      - ./angular-client/src:/app/src

  server:
    build: express-server
    ports:
      - "3000:3000"
    links:
      - database

  # database:
  #   image: mongo
  #   ports:
  #     - "27017:27017"

  database:
    image: 'postgres:11.5-alpine'
    env_file: .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRESS_DB=postgres
    # volumes:
      #   - ./restore.sh:/docker-entrypoint-initdb.d/restore.sh
    ports:
      - "5432:5432"