version: '2'

services:
  client:
    build: angular-client
    ports:
      - "4200:4200"
    volumes:
      - ./angular-client/src:/app/src

  server:
    build: express-server
    ports:
      - "3000:3000"
    links:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"